code --install-extension albymor.increment-selection
code --install-extension alefragnani.bookmarks
code --install-extension alexcvzz.vscode-sqlite
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension bradlc.vscode-tailwindcss
code --install-extension dave-hagedorn.jenkins-runner
code --install-extension dbaeumer.vscode-eslint
code --install-extension dimitribarbot.tailwind-styled-components-extractor
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension esbenp.prettier-vscode
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension golang.go
code --install-extension hans.typescript-react-fc-snippet
code --install-extension hashicorp.terraform
code --install-extension hbenl.vscode-test-explorer
code --install-extension humao.rest-client
code --install-extension ivory-lab.jenkinsfile-support
code --install-extension janjoerke.jenkins-pipeline-linter-connector
code --install-extension jayantasamaddar.clk-storybook-snippets
code --install-extension maarti.jenkins-doc
code --install-extension mhutchie.git-graph
code --install-extension mohsen1.prettify-json
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.test-adapter-converter
code --install-extension norato.storybook-snippets
code --install-extension orsenkucher.vscode-graphql
code --install-extension prisma.prisma
code --install-extension rangav.vscode-thunder-client
code --install-extension recode4dev.jenkinsfile
code --install-extension redhat.ansible
code --install-extension redhat.vscode-yaml
code --install-extension riccardoforina.storybook-helper
code --install-extension ritwickdey.liveserver
code --install-extension rldnrl.typescript-snippet
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension spoonscen.es6-mocha-snippets
code --install-extension styled-components.vscode-styled-components
code --install-extension tyriar.lorem-ipsum
code --install-extension unclebill.vscode-prisme
code --install-extension unifiedjs.vscode-mdx
code --install-extension vadymbiliuk.ts-react-snippets
code --install-extension xabikos.reactsnippets
code --install-extension yzhang.markdown-all-in-one